### ISSUE TITLE
programmer art goes hard

### ISSUE THREAD

**Issue by Matheuxx19** [Matheuxx19/IorguteGregoTemp#1]
resumidamente, ninguem sabe desenhar

**Comment by JJinKm** [comment]
vc n sabe da época q o nosso patrão teve aula de desenho?

**Comment by Matheuxx19** [comment]
True

**Comment by JJinKm** [comment]
primeira issue do iogurte grego resolvido?

**Comment by Matheuxx19** [comment]
Pode ser
